### ISSUE TITLE
Open Beta Bugs : Black Screen : No UI Response

### ISSUE THREAD

**Issue by lilithebowman** [jaquadro/VideoTXL#2]
Using the player on the Open Beta now available I get black screens on all of our players. The UI doesn't respond either.

![20211012111646_1](https://user-images.githubusercontent.com/1637212/136983447-1afa374f-9a46-4b64-a6a2-3f8c3ed65451.jpg)

Here you can see a black screen quad in the background. Nothing has been done to it. Latest versions of VRChat SDK, Udon#, and VideoTXL.

The (i) button also does not respond.

![20211012111838_1](https://user-images.githubusercontent.com/1637212/136983688-64d5c6f6-3b9e-46b3-8065-b75c4923023c.jpg)

Those are the only errors in the logs. API keys if I show anything else so I left out the other logs.

![20211012111939_1](https://user-images.githubusercontent.com/1637212/136983854-30969922-882a-48ee-9323-5d1f3c9f5a0a.jpg)

**Comment by jaquadro** [comment]
Hi, sorry didn't realize there were a couple issues opened on the repo.  If you tried the 1.1.1 or 1.1.2 releases these should have addressed the open beta issues.  However as of a couple days ago vrchat rolled back their breaking changes so the players should be working even without the updates.
