### ISSUE TITLE
VRCDN VOD

### ISSUE THREAD

**Issue by aaronfrancis635** [jaquadro/VideoTXL#6]
Hello,

VRCDN has a VOD service that may be affected by the "SyncPlayer.cs" checking for "vrcdn" and forcing stream mode, best bet here is to check for the full "vrcdn.live" as VODs are run from "vrcdn.video", Hope this helps!

Best Regards,
24 Hour Music

Developer
VRCDN

**Comment by jaquadro** [comment]
Thank you for letting me know, I'll update the check

**Comment by jaquadro** [comment]
Should be addressed in latest beta
