### ISSUE TITLE
[ENHANCEMENT] Set default video mode

### ISSUE THREAD

**Issue by vesturo** [jaquadro/VideoTXL#7]
would be neat if we could set the default Video resolution and if it should be stretched. with custom UVs it's pain tto every time the stream starts set it to stretched.

**Comment by jaquadro** [comment]
default fit just got checked in.  Depending on your use case, it may also be appropriate to copy the TXL video material and set the screen fit on that, then delete the fit property from the property map paired with it to prevent it from being overridden.  The new default setting will be simpler though if you know you're always dealing with the same source res.

Will also look at default for the res.
