### ISSUE TITLE
Latest VRC SDK Update seems to break the player

### ISSUE THREAD

**Issue by vesturo** [jaquadro/VideoTXL#8]
Hey Texel,
The latest update ( 3.1.11 ) always breaks the SendCustomNetworkEvent in your Player as it now requires 3 values instead of 2. Just wanted to give you a headsup :)

How to reproduce:
- Use newest SDK
- import Latest beta
- place any prefab of the Videoplayer in your scene

Code that breaks: SyncPlayer line 200

> public void _InitCheck()
        {
            if (!_initDeserialize)
            {
                DebugLog("Deserialize not received in reasonable time");
                SendCustomNetworkEvent(VRC.Udon.Common.Interfaces.NetworkEventTarget.Owner, "RequestOwnerSync");
            }
        }

**Comment by vesturo** [comment]
oh and just to make sure: the packages that got an update are:

1. "com.vrchat.base" = 3.1.11
2. "com.vrchat.worlds" = 3.1.11
3. "com.vrchat.udonsharp" = 1.1.7

**Comment by jaquadro** [comment]
I've been working on the latest SDK and haven't noticed a change.  I followed your steps on a new project to double-check but I can't find any version of SendCustomNetworkEvent that takes 3 parameters.  Maybe you could provide a screenshot of the error message or snippet from UdonSharpBehaviour.cs?
